Genre.create(name: 'Art')
Genre.create(name: 'Biography')
Genre.create(name: 'Business')
Genre.create(name: 'Chick Lit')
Genre.create(name: 'Children\'s')
Genre.create(name: 'Christian')
Genre.create(name: 'Classics')
Genre.create(name: 'Comics')
Genre.create(name: 'Contemporary')
Genre.create(name: 'Cookbooks')
Genre.create(name: 'Crime')
Genre.create(name: 'Fantasy')
Genre.create(name: 'Fiction')
Genre.create(name: 'Gay and Lesbian')
Genre.create(name: 'Graphic Novels')
Genre.create(name: 'Historical Fiction')
Genre.create(name: 'History')
Genre.create(name: 'Horror')
Genre.create(name: 'Humor')
Genre.create(name: 'Comedy')
Genre.create(name: 'Manga')
Genre.create(name: 'Memoir')
Genre.create(name: 'Music')
Genre.create(name: 'Mystery')
Genre.create(name: 'Non Fiction')
Genre.create(name: 'Paranormal')
Genre.create(name: 'Philosophy')
Genre.create(name: 'Poetry')
Genre.create(name: 'Psychology')
Genre.create(name: 'Religion')
Genre.create(name: 'Romance')
Genre.create(name: 'Science')
Genre.create(name: 'Science Fiction')
Genre.create(name: 'Self Help')
Genre.create(name: 'Suspense')
Genre.create(name: 'Spirituality')
Genre.create(name: 'Sports')
Genre.create(name: 'Thriller')
Genre.create(name: 'Travel')
Genre.create(name: 'Young Adult')
